import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { config } from '../src/config.js';
import type { NormalizedPlace } from '../src/pipeline/types.js';

type PlacesFile = {
  places: NormalizedPlace[];
};

function sqlString(value: string | undefined | null): string {
  if (!value) {
    return 'null';
  }
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlArray(values: string[]): string {
  if (values.length === 0) {
    return 'array[]::text[]';
  }
  return `array[${values.map((value) => sqlString(value)).join(', ')}]`;
}

function exportSqlSeed() {
  const filePath = join(config.outputDir, 'normalized', 'places.json');
  const payload = JSON.parse(readFileSync(filePath, 'utf8')) as PlacesFile;
  const places = payload.places;

  const lines: string[] = [
    '-- Generated by Scrum/scripts/export-sql-seed.ts',
    '-- Run after migration 00002_places.sql',
    'begin;',
    "delete from public.place_sources where true;",
    "delete from public.places where true;",
  ];

  for (const place of places) {
    lines.push(
      `insert into public.places (
  id, place_type, name, name_normalized, country_code, region, city, address_line,
  latitude, longitude, phone, website, google_maps_url, naver_map_url, kakao_map_url,
  status, verification_status, verification_source_count, confidence, raw_category,
  source_apis, merged_from_count, tags, is_published, last_verified_at
) values (
  ${sqlString(place.id)},
  ${sqlString(place.placeType)},
  ${sqlString(place.name)},
  ${sqlString(place.nameNormalized)},
  ${sqlString(place.countryCode)},
  ${sqlString(place.region)},
  ${sqlString(place.city)},
  ${sqlString(place.addressLine)},
  ${place.latitude},
  ${place.longitude},
  ${sqlString(place.phone)},
  ${sqlString(place.website)},
  ${sqlString(place.googleMapsUrl)},
  ${sqlString(place.naverMapUrl)},
  ${sqlString(place.kakaoMapUrl)},
  ${sqlString(place.status)},
  ${sqlString(place.verificationStatus)},
  ${place.verificationSourceCount},
  ${sqlString(place.confidence)},
  ${sqlString(place.rawCategory)},
  ${sqlArray(place.sourceApis)},
  ${place.mergedFromCount},
  ${sqlArray(place.tags)},
  true,
  now()
) on conflict (id) do update set
  name = excluded.name,
  verification_status = excluded.verification_status,
  verification_source_count = excluded.verification_source_count,
  updated_at = now();`,
    );

    for (const source of place.sources) {
      lines.push(
        `insert into public.place_sources (
  place_id, source_api, source_id, source_url, source_query, raw_payload, fetched_at
) values (
  ${sqlString(place.id)},
  ${sqlString(source.api)},
  ${sqlString(source.sourceId)},
  ${sqlString(source.sourceUrl)},
  ${sqlString(source.sourceQuery)},
  ${sqlString(JSON.stringify(source.raw))}::jsonb,
  ${source.fetchedAt ? sqlString(source.fetchedAt) : 'null'}
) on conflict (source_api, source_id) do update set
  place_id = excluded.place_id,
  raw_payload = excluded.raw_payload;`,
      );
    }
  }

  lines.push('commit;');

  const outputPath = join(config.outputDir, 'normalized', 'places-seed.sql');
  writeFileSync(outputPath, `${lines.join('\n\n')}\n`, 'utf8');
  console.log(`SQL seed written: ${outputPath}`);
  console.log(`Places: ${places.length}`);
}

exportSqlSeed();
