#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
REQUEST_KO="$ROOT/01-initial-request-ko.txt"
EVIDENCE="$ROOT/evidence/billing-report-2026-09-12.png"

echo "=== Google Cloud 청구 크레딧 제출 준비 ==="
echo ""
echo "1) 1차 요청 본문(한국어)을 클립보드에 복사합니다..."
pbcopy < "$REQUEST_KO"
echo "   ✓ 클립보드에 복사됨"
echo ""
echo "2) 지원 케이스 페이지를 브라우저에서 엽니다..."
open "https://console.cloud.google.com/support/cases?project=places"
open "https://console.cloud.google.com/billing/011843-972E29-96641B/reports?project=places"
echo "   ✓ 브라우저 열림"
echo ""
echo "3) 증빙 파일 위치를 Finder에서 엽니다..."
open "$ROOT/evidence"
echo "   ✓ evidence 폴더 열림"
echo ""
echo "=== 다음만 하시면 됩니다 ==="
echo "- 지원 케이스 → 결제/청구 문의 생성"
echo "- 본문: Cmd+V (이미 복사됨)"
echo "- 첨부: billing-report-2026-09-12.png"
echo "- 제목: Places API (New) 개발 실수 사용 — 일회성 청구 크레딧 요청"
echo ""
echo "상세: $ROOT/SUBMIT.md"
