import { meetingMockImages } from '@/src/features/tour/mock-data/meeting-mock-images';
import type { DiveMeeting } from '@/src/features/tour/types';

export const mockMeetings: DiveMeeting[] = [
  {
    id: 'meeting-1',
    title: '잠실 잠수풀 버디 모집',
    category: 'buddy',
    environment: 'pool',
    date: '2026-03-15',
    time: '10:00',
    location: '잠실 잠수풀',
    cost: null,
    purpose: 'practice',
    equipmentRental: 'unnecessary',
    hostName: '다이버김',
    hostProfileImageUrl: meetingMockImages.avatars.diverKim,
    coverImageUrl: meetingMockImages.covers.poolPractice,
    maxParticipants: 4,
    currentParticipants: 2,
  },
  {
    id: 'meeting-2',
    title: '제주 서귀포 펀다이빙 버디',
    category: 'buddy',
    environment: 'sea',
    date: '2026-03-22',
    time: '08:30',
    location: '제주 서귀포 문섬',
    cost: 50000,
    purpose: 'fun',
    equipmentRental: 'separate',
    hostName: 'BlueFin',
    hostProfileImageUrl: meetingMockImages.avatars.blueFin,
    coverImageUrl: meetingMockImages.covers.oceanFunDive,
    maxParticipants: 6,
    currentParticipants: 4,
  },
  {
    id: 'meeting-3',
    title: '속초 청정바다 나이트 투어',
    category: 'tour',
    environment: 'sea',
    date: '2026-03-29',
    time: '18:00',
    location: '강원 속초 해변',
    cost: 85000,
    purpose: 'tour',
    equipmentRental: 'included',
    hostName: '속초 다이브센터',
    hostProfileImageUrl: meetingMockImages.avatars.sokchoDiveCenter,
    coverImageUrl: meetingMockImages.covers.nightBeachTour,
    maxParticipants: 8,
    currentParticipants: 5,
  },
  {
    id: 'meeting-4',
    title: '양양 프리다이빙 입문 교육',
    category: 'education',
    environment: 'pool',
    date: '2026-04-05',
    time: '13:00',
    location: '강원 양양 프리다이빙 풀',
    cost: 120000,
    purpose: 'certification',
    equipmentRental: 'included',
    hostName: 'WaveRunner',
    hostProfileImageUrl: meetingMockImages.avatars.waveRunner,
    coverImageUrl: meetingMockImages.covers.poolEducation,
    maxParticipants: 6,
    currentParticipants: 3,
  },
  {
    id: 'meeting-5',
    title: '여수 돌산도 체험다이빙 투어',
    category: 'tour',
    environment: 'sea',
    date: '2026-04-12',
    time: '09:00',
    location: '전남 여수 돌산도',
    cost: 95000,
    purpose: 'experience',
    equipmentRental: 'included',
    hostName: '여수 마린다이브',
    hostProfileImageUrl: meetingMockImages.avatars.yeosuMarineDive,
    coverImageUrl: meetingMockImages.covers.seaExperienceTour,
    maxParticipants: 10,
    currentParticipants: 7,
  },
  {
    id: 'meeting-6',
    title: '성남 잠수풀 OW 연습 모임',
    category: 'education',
    environment: 'pool',
    date: '2026-04-19',
    time: '15:00',
    location: '성남 잠수풀',
    cost: 45000,
    purpose: 'practice',
    equipmentRental: 'separate',
    hostName: '다이브코치',
    hostProfileImageUrl: meetingMockImages.avatars.diveCoach,
    coverImageUrl: meetingMockImages.covers.poolTraining,
    maxParticipants: 5,
    currentParticipants: 1,
  },
];
